services:
  postgres:
    image: postgres:latest
    container_name: postgresPsikoHekim
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: camunda
      POSTGRES_PASSWORD: camunda
      POSTGRES_DB: psiko_bpm
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U camunda"]
      interval: 10s
      timeout: 5s
      retries: 5

  zeebe:
    platform: linux/amd64
    image: camunda/zeebe:latest
    container_name: zeebe-broker
    environment:
      - ZEEBE_LOG_LEVEL=info
      - ZEEBE_BROKER_GATEWAY_ENABLE=true
      - ZEEBE_BROKER_CLUSTER_PARTITIONSCOUNT=1
      - ZEEBE_BROKER_CLUSTER_REPLICATIONFACTOR=1
      - ZEEBE_GATEWAY_SECURITY_ENABLED=false
      - ZEEBE_BROKER_GATEWAY_HOST=0.0.0.0
    ports:
      - "26500:26500"
      - "9600:9600"
    volumes:
      - zeebe_data:/usr/local/zeebe/data

  operate:
    platform: linux/amd64
    image: camunda/operate:latest
    container_name: camunda-operate
    environment:
      - CAMUNDA_OPERATE_ELASTICSEARCH_URL=http://elasticsearch:9200
      - CAMUNDA_OPERATE_ZEEBEELASTICSEARCH_URL=http://elasticsearch:9200
      - CAMUNDA_OPERATE_ZEEBE_GATEWAYADDRESS=zeebe:26500
      - CAMUNDA_OPERATE_ZEEBE_ELASTICSEARCH_CLUSTERNAME=docker-cluster
      - CAMUNDA_OPERATE_CSRFPREVENTIONENABLED=false
    ports:
      - "8081:8080"
    depends_on:
      elasticsearch:
        condition: service_healthy
      zeebe:
        condition: service_started

  tasklist:
    platform: linux/amd64
    image: camunda/tasklist:latest
    container_name: camunda-tasklist
    environment:
      - CAMUNDA_TASKLIST_ZEEBE_GATEWAYADDRESS=zeebe:26500
      - CAMUNDA_TASKLIST_ZEEBE_RESTADDRESS=http://zeebe:8080
      - CAMUNDA_TASKLIST_ELASTICSEARCH_URL=http://elasticsearch:9200
      - CAMUNDA_TASKLIST_ZEEBEELASTICSEARCH_URL=http://elasticsearch:9200
      - CAMUNDA_TASKLIST_CSRFPREVENTIONENABLED=false
    ports:
      - "8084:8080"
    depends_on:
      elasticsearch:
        condition: service_healthy
      zeebe:
        condition: service_started

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.17.2
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - "9200:9200"
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:9200/_cat/health || exit 1"]
      interval: 30s
      retries: 5
      start_period: 30s
      timeout: 10s

volumes:
  postgres_data:
  elasticsearch_data:
  zeebe_data: 